Feat/new jupyter doc and hierarcy
DesignSafe-CI/DS-User-Guide pull request #30
Opened 2024-04-12 19:17 UTC by zwyll

Updated the document for DesignSafe Jupyter HPC.

2024-04-12 19:40 UTC, wesleyboar reviewed
I like not using ` (backtick).

But, I suspect we should be using " (quotes) or nothing instead of ** (bold) and * (italic), but I defer to @susanunit's judgement.

2024-04-23 17:16 UTC, wesleyboar requested changes
As discussed privately, let's use quotations for text form an interface.

2024-04-23 17:16 UTC, wesleyboar commented on user-guide/docs/tools/jupyterhub/jupyterlabhpc.md
> +3. Once your job starts, the Job Status bar will show status as "RUNNING" and a small window will pop up. Then click the *CONNECT!* button to connect to your interactive session, i.e., JupyterLab.
To match [private answer](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713808703941429) from [private confirmation request](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713196766860919) for desired punctuation:

```suggestion
3. Once your job starts, the Job Status bar will show status as "RUNNING" and a small window will pop up. Then click the "CONNECT!" button to connect to your interactive session, i.e., JupyterLab.
```

2024-04-23 17:16 UTC, wesleyboar commented on user-guide/docs/tools/jupyterhub/jupyterlabhpc.md
> +1. Go to [DesignSafe website](https://www.designsafe-ci.org) and sign in to your DesignSage account. Then click *Use DesignSafe* > *Tools & Applications* > *Analysis* > *Jupyter* and select *Jupyter
To match [private answer](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713808703941429) from [private confirmation request](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713196766860919) for desired punctuation:

```suggestion
1. Go to [DesignSafe website](https://www.designsafe-ci.org) and sign in to your DesignSage account. Then click "Use DesignSafe" > "Tools & Applications" > "Analysis" > "Jupyter" and select "Jupyter Lab HPC (GPU)".
```

2024-04-23 17:16 UTC, wesleyboar commented on user-guide/docs/tools/jupyterhub/jupyterlabhpc.md
> +2. Once define your maximum Job runtime (no more than 48 hours) and Job name, click the *Run* buttton so the job will be submitted. Then you can monitor your job status on the right column.
To match [private answer](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713808703941429) from [private confirmation request](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713196766860919) for desired punctuation:

```suggestion
2. Once define your maximum Job runtime (no more than 48 hours) and Job name, click the "Run" buttton so the job will be submitted. Then you can monitor your job status on the right column.
```

2024-04-23 17:16 UTC, wesleyboar commented on user-guide/docs/tools/jupyterhub/jupyterlabhpc.md
> +1. Navigate to the *HPCWork* folder. You need to place all your data/codes/Jupyter Notebooks inside this folder.
To match [private answer](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713808703941429) from [private confirmation request](https://tacc-team.slack.com/archives/C06S93KKA5R/p1713196766860919) for desired punctuation:

```suggestion
1. Navigate to the "HPCWork" folder. You need to place all your `data/codes/Jupyter Notebooks` inside this folder. 
```

Also includes extra `bit of formatting`.

2024-04-23 17:18 UTC, wesleyboar approved these changes

2024-04-25 17:52 UTC, cockerilltim commented
Approved.

2024-04-25 17:54 UTC, cockerilltim approved these changes
approved

2024-04-25 17:54 UTC, merged