Added in-core on DesignSafe User Guide
DesignSafe-CI/DS-User-Guide pull request #35
Opened 2024-06-06 12:01 UTC by rinconraul

## Overview
The User Guide for IN-CORE on DesignSafe has been added to the documentation in Tools/Simulations.
…

## New files
We have added the in-core.md and required images for the user guide.

## Changes
The simulation.md file has been updated to include the _in-core.md_. Alphabetic order has been preserved.

2024-06-06 16:42 UTC, rinconraul commented
Added also the previous use case, here called `usecase_JN_viz.md`
Also included the use case path within the indexers

2024-06-06 19:01 UTC, wesleyboar requested changes
DS-User-Guide has idiosyncrasies and new standards. Please review my comments.

You can use GitHub UI to [apply suggested changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) or make commits in your workspace.

GitHub does not render `.md` as the website will. You can [test how website will show it](https://github.com/DesignSafe-CI/DS-User-Guide?tab=readme-ov-file#local-testing).

<details><summary>"Before & After" Screenshots</summary>

| before | after |
| - | - |
| ![before](https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/c6ba13e5-1990-4944-8f28-2fce57877c61) | ![after](https://github.com/DesignSafe-CI/DS-User-Guide/assets/62723358/377a24be-655b-4fbd-8326-b545b1294d02) |

</details>

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +Jupyter notebooks on DS Juypterhub <a href="https://jupyter.designsafe-ci.org/hub/user-redirect/lab/tree/NHERI-Published/PRJ-3939/visualization_risk_resilience.ipynb"><img src="https://raw.githubuser
Use markdown not HTML.[^1] I constructed this by referencing [other files that use this](https://github.com/search?q=repo%3ADesignSafe-CI%2FDS-User-Guide+%22Open+in+DesignSafe%22&type=code).

```suggestion
The examples presented make use of the following DesignSafe resources: <br>
Jupyter notebooks on DS Juypterhub [![Open In DesignSafe](https://raw.githubusercontent.com/geoelements/LearnMPM/main/DesignSafe-Badge.svg)](https://jupyter.designsafe-ci.org/hub/user-redirect/lab/tree/NHERI-Published/PRJ-3939/visualization_risk_resilience.ipynb)
```

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +Keywords: visualization; risk and resilience; infrastructure systems; static, interactive, and animated maps and figures, effective communication
Italicize keywords as is done on other use cases e.g.
- [Seismic Response of Concrete Walls](https://www.designsafe-ci.org/user-guide/usecases/seismicusecases/#seismic-response-of-concrete-walls)
- [Field Sensing Wind Events](https://www.designsafe-ci.org/user-guide/usecases/windstormsurgeusecases/#field-sensing-wind-events).

You are correct to use the word "Keywords" (despite the examples).

```suggestion
_Keywords: visualization; risk and resilience; infrastructure systems; static, interactive, and animated maps and figures, effective communication_
```

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +            margin: auto;"/>
1. Use markdown not HTML.[^1]
2. Path to image must be up one directory to render on site.[^2]

The solution below will add an `id` attribute[^2] to the `img` (same effect as `<a name>`[^3]).

```suggestion
![Risk and resilience outputs and stakeholder visualization needs](../img/Figure1_viz.jpg){: id="Fig1" style="display: block;max-width: 65%;height: auto;margin: auto;" }
```

> [!WARNING]
> Inline styles are deprecated, but I retained yours via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: I know this is unintuitive and wrong and we are sorry. [It has bitten others.](https://github.com/DesignSafe-CI/DS-User-Guide/pull/7) I will fix this.
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +<a href="https://jupyter.designsafe-ci.org/hub/user-redirect/lab/tree/NHERI-Published/PRJ-3939/visualization_risk_resilience.ipynb"><img src="https://raw.githubusercontent.com/geoelements/LearnMPM/ma
Use markdown not HTML.[^1] I constructed this by referencing [other files that use this](https://github.com/search?q=repo%3ADesignSafe-CI%2FDS-User-Guide+%22Open+in+DesignSafe%22&type=code).

```suggestion
[![Open in DesignSafe](https://raw.githubusercontent.com/geoelements/LearnMPM/main/DesignSafe-Badge.svg)](https://jupyter.designsafe-ci.org/hub/user-redirect/lab/tree/NHERI-Published/PRJ-3939/visualization_risk_resilience.ipynb)
```

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +### 1. Plotting distributed infrastructure using static plots <a name="Title1"></a>
Use markdown not HTML.[^1]

The solution below will add an `id` attribute[^2] to the `h3` (same effect as `<a name>`[^3]).

```suggestion
### 1. Plotting distributed infrastructure using static plots { #Title1 }
```

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: Via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +### 2. Interactive exploration of spatially distributed information  <a name="Title2"></a>
Use markdown not HTML.[^1]

The solution below will add an `id` attribute[^2] to the `h3` (same effect as `<a name>`[^3]).

```suggestion
### 2. Interactive exploration of spatially distributed information  { #Title2 }
```

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: Via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes)).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +### 3. Creation of animated graphs and GIFs  <a name="Title3"></a>
Use markdown not HTML.[^1]

The solution below will add an `id` attribute[^2] to the `h3` (same effect as `<a name>`[^3]).

```suggestion
### 3. Creation of animated graphs and GIFs  { #Title3 }
```

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: Via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +</table>
1. Use markdown not HTML.[^1]
2. Path to image must be up one directory to render on site.[^2]
3. Missing a `Fig4` id attribute. I added it.[^2]

```suggestion
<style>
/* TODO: Remove this style and class after redesign */
.image-as-data { background-color: white !important; }
</style>

| (a) Example of a graph animated with interactive widgets { #Fig4 } | (b) Example of a ‘gif’ animation |
| - | - |
| ![recovery graph 1](../img/Figure4_viz.jpg){: style="display: block; max-width: 70%; height: auto; margin: auto;" } {: .image-as-data } | ![recovery graph animation](../img/recovery_trajectory_viz.gif){: style="display: block; max-width: 100%; height: auto; margin: auto;" } {: .image-as-data } |
```

> [!NOTE]
> No need to set white table row bkgd, because first data row will be white after redesign ([example](https://designsafeci-next.tacc.utexas.edu/user-guide/tools/simulation/#adcirc-command-line-options)).

> [!WARNING]
> Inline styles are deprecated, but I retained yours via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: I know this is unintuitive and wrong and we are sorry. [It has bitten others.](https://github.com/DesignSafe-CI/DS-User-Guide/pull/7) I will fix this.
[^3]: Via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).
Unnecessary `<br />`'s. This list will render the same on the website with and without them.

```suggestion
* Please cite [Rincon and Padgett (2023)](https://doi.org/10.17603/ds2-a74m-g031) to acknowledge the use of resources from this use case.

* Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.

* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).
```

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +            margin: auto;"/>
1. Use markdown not HTML.[^1]
2. Path to image must be up one directory to render on site.[^2]

The solution below will add an `id` attribute[^2] to the `img` (same effect as `<a name>`[^3]).

```suggestion
![Visualization of static plots](../img/Figure2_viz.jpg){: id="Fig2" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```

> [!WARNING]
> Inline styles are deprecated, but I retained yours via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: I know this is unintuitive and wrong and we are sorry. [It has bitten others.](https://github.com/DesignSafe-CI/DS-User-Guide/pull/7) I will fix this.
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +            margin: auto;"/>
1. Use markdown not HTML.[^1]
2. Path to image must be up one directory to render on site.[^2]

The solution below will add an `id` attribute[^2] to the `img` (same effect as `<a name>`[^3]).

```suggestion
![Visualization of interactive plots](../img/Figure3_viz.jpg){: id="Fig3" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```

> [!WARNING]
> Inline styles are deprecated, but I retained yours via [`python-markdown` "Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)".

[^1]: [Markdown (extended)](https://www.markdownguide.org/extended-syntax/) (we use [mkdocs'](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)) allows consistent input and output (which benefits maintenance and updates).
[^2]: I know this is unintuitive and wrong and we are sorry. [It has bitten others.](https://github.com/DesignSafe-CI/DS-User-Guide/pull/7) I will fix this.
[^3]: The `name` attribute is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#deprecated_attributes).

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +3. [Creation of animated graphs and GIFs.](#Title3)
New line required to start a list.[^1]

```suggestion
The following structure is used:

1. [Plotting distributed infrastructure using static plots.](#Title1)
2. [Interactive exploration of spatially distributed information.](#Title2)
3. [Creation of animated graphs and GIFs.](#Title3)
```

[^1]: The markdown interpreter used by the website is stricter than GitHub's.

2024-06-06 19:01 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +    b. CSV files with the values of the peak ground acceleration (PGA) at the grid and bridge locations for one earthquake event realization (magnitude 7.1).
1. New line required to start a list.[^1]
2. Nested lists must use either numbers (`    1. `) or bullets (`    * `, `    - `).
3. For a nested list to use `a.` and `b.` (not standard yet), use `<style>` (for now). 

```suggestion

<style>
/* FAQ: The ` li` is required because `theme.css` sets `list-style` on `li` */
#input-files ~ ol ol li { list-style: upper-alpha; }
</style>

1. Hazard:
    1. CSV files with a mesh grid and bridges’ locations.
    2. CSV files with the values of the peak ground acceleration (PGA) at the grid and bridge locations for one earthquake event realization (magnitude 7.1).
```

[^1]: The markdown interpreter used by the website is stricter than GitHub's.

2024-06-06 19:08 UTC, wesleyboar commented on user-guide/docs/tools/simulation.md
> +{% include-markdown 'simulation/in-core.md' %}
@silviamazzoni, should this content be included on a page that is accessible via the navigation?

I can see the content on http://localhost:8000/user-guide/tools/simulation/, but that page does not show in nav.

2024-06-06 20:47 UTC, rinconraul commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +            margin: auto;"/>
Got it!! This was an old (9-10 months) use case that ended up moving here today... sorry for the HTML!
About #2, agree! there are more use case using directly "img/Figname.jpg"... I checked that and probably ended up using the incorrect case.

2024-06-06 20:52 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +            margin: auto;"/>
Yeah, I just learned this probably came from https://github.com/DesignSafe-CI/DS_Use_Case_template, which I forgot to deprecate. (I'll deprecate it soon.) Please excuse my terseness — it's the only way I can ever get through longer PRs while still being informative.

2024-06-06 20:59 UTC, rinconraul commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +</table>
@wesleyboar is this TODO for me? Or an internal TODO

2024-06-06 21:06 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +</table>
Internal. (The redesign is #31.)

2024-06-06 21:28 UTC, wesleyboar reviewed
Agh. The image paths work if I directly visit the page[^1], but not if I visit it via navbar[^2].

[^1]: https://www.designsafe-ci.org/user-guide/usecases/padgett/usecase_JN_viz/
[^2]: https://www.designsafe-ci.org/user-guide/usecases/dataanalyticsusecases/

I've suggested, and will commit, the fixes. Hold on a sec.

2024-06-06 21:28 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +![Risk and resilience outputs and stakeholder visualization needs](../img/Figure1_viz.jpg){: id="Fig1" style="display: block;max-width: 65%;height: auto;margin: auto;" }
```suggestion
![Risk and resilience outputs and stakeholder visualization needs](/user-guide/usecases/padgett/img/Figure1_viz.jpg){: id="Fig1" style="display: block;max-width: 65%;height: auto;margin: auto;" }
```

2024-06-06 21:28 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +![Visualization of static plots](../img/Figure2_viz.jpg){: id="Fig2" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```suggestion
![Visualization of static plots](/user-guide/usecases/padgett/img/Figure2_viz.jpg){: id="Fig2" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```

2024-06-06 21:28 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +![Visualization of interactive plots](../img/Figure3_viz.jpg){: id="Fig3" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```suggestion
![Visualization of interactive plots](/user-guide/usecases/padgett/img/Figure3_viz.jpg){: id="Fig3" style="display: block;max-width: 85%;height: auto;margin: auto;" }
```

2024-06-06 21:28 UTC, wesleyboar commented on user-guide/docs/usecases/padgett/usecase_JN_viz.md
> +| ![recovery graph 1](../img/Figure4_viz.jpg){: style="display: block; max-width: 70%; height: auto; margin: auto;" } {: .image-as-data } | ![recovery graph animation](../img/recovery_trajectory_viz.
```suggestion
| ![recovery graph 1](/user-guide/usecases/padgett/img/Figure4_viz.jpg){: style="display: block; max-width: 70%; height: auto; margin: auto;" } {: .image-as-data } | ![recovery graph animation](/user-guide/usecases/padgett/img/recovery_trajectory_viz.gif){: style="display: block; max-width: 100%; height: auto; margin: auto;" } {: .image-as-data } |
```

2024-06-06 21:32 UTC, wesleyboar approved these changes
**Works.** Content will be accessible at:

- https://www.designsafe-ci.org/user-guide/tools/simulation/ ⚠️
- https://www.designsafe-ci.org/user-guide/usecases/dataanalyticsusecases/
- https://www.designsafe-ci.org/user-guide/usecases/padgett/usecase_JN_viz/ ⚠️

⚠️ User can not navigate to it via navbar.

2024-06-06 21:32 UTC, merged

2024-06-07 19:38 UTC, wesleyboar commented
Image paths reverted/fixed in #37.

I am sorry for the confusion. I'll step back from image paths until I am more certain of my tests.